import assert from 'node:assert/strict';
import vm from 'node:vm';
import {readFileSync} from 'node:fs';
const c=vm.createContext({});vm.runInContext(readFileSync(new URL('../analysis-model.js',import.meta.url),'utf8'),c);const M=c.PulseModel;
const dates=M.range('2026-09-24',14);
const base={summaries:dates.map(date=>({date,collectedAt:date+'T04:00:00+09:00'})),articles:[{key:'old',publishedAt:'2026-09-10',category:'その他'},{key:'new',publishedAt:'2026-09-20'},{key:'deleted'}],articleHistory:dates.flatMap((date,i)=>[{key:'old',date,pv:100+i*2,likes:i,comments:0},...(i>=10?[{key:'new',date,pv:999,likes:4,comments:1}]:[])]),followers:dates.map((date,i)=>({date,followerCount:100+i}))};
const m=M.create(base),p=M.period(m,7);
assert.equal(m.articles.length,2,'absent current articles must not appear');
assert.equal(p.sum('pv'),14,'new article without baseline must not be assumed zero');
assert.equal(p.eligible.length,1);assert.equal(p.comparable.length,1);assert.equal(p.prev('pv'),14);assert.equal(p.compared('pv'),14);
assert.equal(M.delta(m,'new',m.end,7),null);
assert.equal(p.items.find(a=>a.key==='new').provisionalDormant,true);
const growing=structuredClone(base);growing.articleHistory.find(r=>r.key==='new'&&r.date==='2026-09-24').pv=1000;
assert.equal(M.period(M.create(growing),7).items.find(a=>a.key==='new').provisionalDormant,false,'growing new articles must not be labelled dormant');
assert.equal(M.followerDelta(m,m.end,7),7);
const gap=structuredClone(base);gap.articleHistory=gap.articleHistory.filter(r=>!(r.key==='old'&&r.date==='2026-09-20'));
assert.equal(M.delta(M.create(gap),'old','2026-09-24',7),null,'intermediate missing date cannot be silently bridged');
const nil=structuredClone(base);nil.articleHistory.find(r=>r.key==='old'&&r.date==='2026-09-20').pv=null;
assert.equal(M.period(M.create(nil),7).sum('pv'),null,'null must not become zero');
const decline=structuredClone(base);decline.articleHistory.find(r=>r.key==='old'&&r.date==='2026-09-24').pv=0;
assert.equal(M.period(M.create(decline),7).sum('pv'),-114,'observed corrections are preserved');
assert.equal(M.period(m,30).sum('pv'),null,'insufficient 30-day history must remain unavailable');
assert.equal(M.aligned(m,m.articles[0],7).row.pv,114);
assert.match(M.aligned(m,m.articles[1],7).reason,/取得待ち/);
assert.match(M.aligned(m,{key:'old',publishedAt:'2020-01-01'},7).reason,/記録なし/);
const followGap=structuredClone(base);followGap.followers[12].followerCount=null;
assert.equal(M.followerDelta(M.create(followGap),'2026-09-24',7),null);
assert.equal(M.numeric(0),0);assert.equal(M.numeric(null),null);
console.log('Missing-data, cohort, negative correction, date-alignment and publication-state checks passed.');
