import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {run,fixture} from './harness.mjs';
const input=process.env.PULSE_TEST_DATA?JSON.parse(readFileSync(process.env.PULSE_TEST_DATA,'utf8')):fixture;
const ui=await run(input);
assert(ui.context.notePulseData,'render must finish successfully');
for(const id of ['summaryCards','overviewCharts','ageMix','ledger','comparison','officialCards','openCampaignList'])assert(ui.elements.get('#'+id).innerHTML.length>0,id+' must render');
ui.eval('drawDetail(period.items[0].key)');
assert(ui.elements.get('#articleDetail').innerHTML.includes('成長曲線'));
ui.eval('toggleCompare(period.items[0].key)');
assert(ui.elements.get('#comparison').innerHTML.includes('比較項目'));
ui.eval('toggleCompare(period.items[0].key)');
assert(ui.elements.get('#comparison').innerHTML.includes('選んでください'));
ui.elements.get('#period').value='30';ui.eval('draw()');
assert(ui.elements.get('#periodLabel').textContent.includes('前期間'));
ui.elements.get('#search').value='no-matching-title-123';ui.eval('drawLedger()');
assert(ui.elements.get('#ledger').innerHTML.includes('この条件に合う'));
assert(ui.elements.get('#overviewCharts').innerHTML.includes('フォロワー数'));
const offline=await run(fixture,true);
assert.match(offline.elements.get('#status').textContent,/取得できません/);
assert.equal(offline.elements.get('#retry').hidden,false);
console.log('Rendering, period controls, detail, comparison, search and error states passed.');
